Rails.application.routes.draw do
  get 'posts/ciftlik'
  get 'posts/tarimvebalik'
  get 'posts/tarimsalisletme'
  get 'posts/iletisim'
  get 'posts/bitcoin'
  get 'posts/bist'
  get 'posts/euro'
  get 'posts/dolar'
  get 'posts/gramaltin'
  get 'posts/digitalpara'
  get 'posts/markapatent'
  get 'posts/avrupabirlikdestek'
  get 'posts/tubitakdestek'
  get 'posts/kalkinmaajansdestek'
  get 'posts/kkydpdestek'
  get 'posts/tkdkdestek'
  get 'posts/kosgeb'
  get 'posts/danismanlikhizmet'
  get 'posts/digitalgirisimcilik'
  get 'posts/index'
	resources :posts
	root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end